name: Games for Windows and the DirectX SDK blog

title: Games for Windows and the DirectX SDK blog

description: Technical tips, tricks, and news about game development for Microsoft platforms including desktop, Xbox, and UWP

author: Chuck Walbourn

url: https://walbourn.github.io/

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/walbourn/walbourn.github.io/master/images/X_jpg.jpg

# Includes an icon in the footer for each username you enter
footer-links:
  github: walbourn
  stackoverflow: users/3780494/chuck-walbourn

permalink: /:title/

markdown: kramdown

theme: jekyll-theme-midnight

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed

google_analytics: "G-X026T44B1S"
